# Generated by Django 3.2 on 2022-07-16 15:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Etudiant',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('nom', models.CharField(max_length=50)),
                ('prenom', models.CharField(max_length=70)),
                ('age', models.IntegerField()),
                ('ecole', models.CharField(max_length=20)),
            ],
        ),
    ]
